#!/bin/bash

# specifically no -e flag!
set -x

if ssh-add -L | grep macpc ; then
  echo ok # nothing
else
  ssh-add ~/.ssh/mac_id_rsa_2
fi

cd ~/projects/ruby/microsites3

branch=`git branch | grep -e "^*" | cut -d' ' -f 2`

bundle > /dev/null &&

RAILS_ENV=production bundle exec rake assets:precompile &&

git checkout master &&
git merge "$branch" &&
git add . &&
git commit -m "autobuild `date "+%Y%m%d"`" 
git push origin master &&
git checkout "$branch" &&
git merge master &&
git push &&

bundle exec cap do deploy

echo "microsites3 build ok"
