#!/bin/bash

set -ex

cd /home/ubuntu/projects/microsites3_api
git reset origin/master --hard
git pull
/home/ubuntu/.rbenv/versions/2.3.1/bin/bundle
/home/ubuntu/.rbenv/versions/2.3.1/bin/bundle update ishapi
/home/ubuntu/.rbenv/versions/2.3.1/bin/bundle update ish_models
sudo service microsites3_api-app restart
sleep 3
service microsites3_api-app status
